{{ if .Values.dataPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metersphere-data-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-controller-data-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}